# Generated by Django 4.1.3 on 2022-11-22 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('composition', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='compositions',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='compositions',
            name='percentage',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
    ]
