# Generated by Django 4.1.3 on 2022-11-29 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('composition', '0003_alter_compositions_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compositions',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='compositions',
            name='name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='compositions',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
