# Generated by Django 4.1.3 on 2022-11-29 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('composition', '0004_alter_compositions_date_alter_compositions_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compositions',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='composition.materials'),
        ),
    ]
