# Generated by Django 4.1.3 on 2022-11-30 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('composition', '0006_remove_compositions_material_materials_compositions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materials',
            name='compositions',
        ),
        migrations.AddField(
            model_name='compositions',
            name='material',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='composition.materials'),
        ),
    ]
