# Generated by Django 4.1.3 on 2022-11-30 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('composition', '0007_remove_materials_compositions_compositions_material'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compositions',
            name='material',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='composition.materials'),
        ),
    ]
